#######
##
##    Plugin version: 1.0.3
##    Devblog:
##    1. The main plugin config has been updated to make it easier for beginners
##    2. Refactoring the code for a more professional version
##    3. Added editing of messages such as: Warnings, Help messages and more
##    4. NEW! Added a BossBar message system at the top of the screen
##       you can change the bossbar settings at the bottom of the config
##    5. More code optimization. Many old solutions were removed to optimize the plugin
##
##    Developer:      Mexaa_
##    Github:         https://github.com/Mexaas
##    Spigotmc.ru:    https://spigotmc.ru/members/mexaa_.79484/#about
##    Spigotmc.org:   https://www.spigotmc.org/members/mexaa_.1196753/
##    Modrinth:       https://modrinth.com/user/Mexaa_
##
#######

# Available serializers:
#  LEGACY_AMPERSAND -> &aHello, World!                  1.16.5 +
#  LEGACY_SECTION -> §aHello, World!                    1.16.5 +
#  MINIMESSAGE -> <bold><red>Hello World</red></bold>   1.18   +
prefix: "&#7855CBM&#7354CAE&#6E53CAX&#6853C9C&#6352C8o&#5E51C8o&#5950C7l&#544FC7d&#4F4EC6o&#494EC5w&#444DC5ns&#3F4CC4 &8» &r"
messages:
  # General pattern of actionbar message
  # Supports plugin placeholders:
  # %time% - remaining time to use command again
  # %command% - blocked command name. Example: free
  no-permission: "&x&D&1&C&3&E&9You do &x&E&F&4&7&4&7not have permission &x&D&1&C&3&E&9to use this &x&E&F&4&7&4&7command!&r"
  reload-success: "&x&D&1&C&3&E&9Plugin was &x&3&D&D&B&6&8reloaded!"
  cooldown-active: "&x&D&1&C&3&E&9Please wait &x&3&D&D&B&6&8%time% &x&D&1&C&3&E&9before using &x&3&D&D&B&6&8%command%!"
  actionbar-message: "&x&3&D&D&B&6&8%time% &x&D&1&C&3&E&9remaining for &x&3&D&D&B&6&8%command%&f!"
  bossbar-message: "&x&3&D&D&B&6&8%time% &x&D&1&C&3&E&9remaining for &x&3&D&D&B&6&8%command%&f!"
  warning-message: "&x&E&0&B&E&6&1WARNING: &x&D&1&C&3&E&9Value in &x&E&0&B&E&6&1actionbar or bossbar duration should be lower, than &x&E&0&B&E&6&131"
  help-message:
    - "&7"
    - "               &x&6&5&5&F&D&BM&x&6&7&5&F&D&6E&x&6&9&6&0&D&2X&x&6&B&6&0&C&DC&x&6&D&6&0&C&8o&x&6&F&6&1&C&3o&x&7&0&6&1&B&Fl&x&7&2&6&2&B&Ad&x&7&4&6&2&B&5o&x&7&6&6&2&B&0w&x&7&8&6&3&A&Cn&x&7&A&6&3&A&7s"
    - "&7"
    - "&7   /mexcooldowns reload &8[Plugin reload]"
    - "&7"

# Enables the command delay notification in the ActionBar (above the player's slotbar). Disables chat messages
actionbar:
  # Responsible for: whether the function is enabled or not. Can be false or true
  enabled: false # or true
  # This function controls the duration of the ActionBar display. It cannot be longer than 30
  # The duration value is specified in SECONDS
  duration: 5

# Enabled the command delay notification in the BossBar. Disables chat messages
bossbar:
  # Responsible for: whether the function is enabled or not. Can be false or true
  enabled: false
  # This function controls the duration of the BossBar display. It cannot be longer than 30
  # The duration value is specified in SECONDS
  duration: 5

# Time display format. Can be replaced with any word as your imagination allows
format:
  # Display in seconds, minutes, hours, and days.
  # Example: 32 available coffee remaining for /menu!
  seconds: "seconds"
  minutes: "minutes"
  hours: "hours"
  days: "days"

# Basic settings. The plugin will search for command inputs by the specified group and command name, and apply a delay if a match is found
groups:
  # Lowercase group name from your LuckPerms
  default:
    # The name of the preferred command that you want to block
    # Example:
    # help: 10
    any_plugin_command: 5
  # An example of using the admin group
  admin:
    # The bypass setting has two modes: false or true. It is responsible for ignoring the delay for administrators
    bypass: true # or false