###############################################################################################################
#
#    Developer:      Mexaa_
#    Github:         https://github.com/Mexaas
#    Spigotmc.ru:    https://spigotmc.ru/members/mexaa_.79484/#about
#    Spigotmc.org:   https://www.spigotmc.org/members/mexaa_.1196753/
#    Modrinth:       https://modrinth.com/user/Mexaa_
#
###############################################################################################################
#
#    Placeholders:
#    %command% - The command on cooldown
#    %time%    - The remaining time on the cooldown
#
#    Permissions:
#    mexcooldowns.reload
#
###############################################################################################################
#
#          UPDATE 1.0.2                 <-------
#
#  - MiniMessages [<bold><red>Message ...]
#  - Legacy formats [&a&lMessage ...]
#  - ActionBar messages                   <- Turn off chat messages
#  - More optimization
#  - Fixed suspicious code
#  - Warnings to optimize infinite duration of actionbars
#
###############################################################################################################

###
#    Formats:
#
#    MiniMessage
#    Legacy
###
prefix: "<gradient:#7F5CFC:#7932BF><shadow:#280886:1>MEXCooldowns</shadow></gradient> <dark_gray>Â» "

actionbar:
  enabled: false  # Default value: false
  message: "&x&3&D&D&B&6&8%time% &x&D&1&C&3&E&9remaining for &x&3&D&D&B&6&8%command%&f!"
  duration: 5     # Show duration of ActionBar

format:
  seconds: "seconds"
  minutes: "minutes"
  hours: "hours"
  days: "days"

messages:
  no-permission: "&x&D&1&C&3&E&9You do &x&E&F&4&7&4&7not have permission &x&D&1&C&3&E&9to use this &x&E&F&4&7&4&7command!&r"
  reload-success: "&x&D&1&C&3&E&9Plugin was &x&3&D&D&B&6&8reloaded!"
  cooldown-active: "&x&D&1&C&3&E&9Please wait &x&3&D&D&B&6&8%time% &x&D&1&C&3&E&9before using &x&3&D&D&B&6&8%command%!"

groups:
  default:                     #  Highest priority group name (LuckPerms support)
    any_plugin_command: 5      #  command:seconds_cooldown (CMI commands doesn't work, please set command cooldown in CMI config)
  admin:                       #
    bypass: true               # Bypass the cooldown