###############################################################################################################
#
#
#
#
#
#
#
#
#          Russian version                                          English version
#
#                            Plugin for creating command cooldowns
#    LuckPerms,                      with LuckPerms support,
#                          offering full configuration of the config file,
#                                    formats, messages, and more
#
###############################################################################################################
#
#                                                 Permissions:
#    mexcooldowns.reload  [        mexcooldowns.reload  [Plugin reload]
#
###############################################################################################################
#
#    Developer:      Mexaa_
#    Github:         https://github.com/Mexaas
#    Spigotmc.ru:    https://spigotmc.ru/members/mexaa_.79484/#about
#    Spigotmc.org:   https://www.spigotmc.org/members/mexaa_.1196753/
#    Modrinth:       https://modrinth.com/user/Mexaa_
#
###############################################################################################################
prefix: "&x&6&5&5&F&D&BMEXCooldowns &8&r"

format:
  seconds: "seconds"
  minutes: "minutes"
  hours: "hours"
  days: "days"

messages:
  no-permission: "&fYou do &cnot have permission &fto use this &ccommand!&r"
  reload-success: "&fPlugin was &areloaded!"
  cooldown-active: "&fPlease wait &a%time% &fbefore using &a%command%&f!"

groups:
  default:        #  Highest priority group name (LuckPerms support)
    spawn: 10     #  command:seconds_cooldown (CMI commands doesn't work, please set command cooldown in CMI config)
  admin:          #
    bypass: true  # Bypass the cooldown